dependencies:
  - name: minio
    version: 7.2.1
    repository: https://helm.min.io
    condition: minio.enabled
  - name: molgenis-rserve
    version: 0.1.2
    repository: https://registry.molgenis.org/repository/helm
    condition: molgenis-rserve.enabled
  - name: molgenis-auth
    version: ^0.1.1
    repository: https://registry.molgenis.org/repository/helm
    condition: molgenis-auth.enabled